### ISSUE TITLE
Hides target's parent

### ISSUE THREAD

**Issue by Hotklou2404** [SheepCommander/gd-SoloVisibility#1]
The plugin seems to be working exactly as described. In fact, perhaps it works a little too well. The problem is it hides the parent node of the target as well, meaning the target is hidden anyways.

For example, I have different kinds of props sorted under different parent nodes. And if I use this plugin's hide function it hides everything except the prop I have selected, including the parent of this prop.

**Comment by SheepCommander** [comment]
Thank you for the report! I actually became aware of it earlier today, and I'm rather embarrassed that I didn't catch it sooner..

> The reason it wasn't caught is because I usually group related nodes underneath a plain Node. Plain Nodes do not have a `visible` properry, and thus changes to `visible` don't propagate down the scene tree if you use a Node in-between.
> 
> In hindsight it should've been obvious that this would be an issue, but at the time when things appeared to be working as intended I assumed it was a quirk of setting the `visible` property directly instead of doing it through the `hide()` method indirectly

> (using plain Nodes would technically be a temporary workaround, but I plan to rush the logic to keep Parent nodes shown as soon as possible)

**Comment by SheepCommander** [comment]
JUST FINISHED THIS (I wasted numerous hours on looking for a solution for #3 and was also working on #2 at the same time)

**Comment by SheepCommander** [comment]
@Hotklou2404 This has [just now been fixed](https://github.com/SheepCommander/gd-SoloVisibility/commit/5f1e26ae2d1ec380f5318926a42f744e0e31e2ee)! It should be live on the AssetLibrary by tomorrow, or you can update it manually from the repo!

(#2 I'm aiming to get done either tonight or tomorrow)
