### ISSUE TITLE
Suggestion: Show all

### ISSUE THREAD

**Issue by Hotklou2404** [SheepCommander/gd-SoloVisibility#2]
It might be nice to have a function that kind of does the opposite - press a slightly different hotkey to show all nodes again. Instead of relying on godot's undo function to do this, the plugin could have something like that built in. `Ctrl + H`, `Shift + Ctrl + H` or `Shift + Alt + H` maybe?

**Comment by SheepCommander** [comment]
Yes! This is a planned feature that I think I may be able to implement by the end of the week.

> The problem is I need to find the last used CacheID, local to the scene that's currently being edited; but I do not currently know a good way to uniquely and persistently identify a scene in the Editor.
>
> Using the resource path as an identifier will break every time the scene is renamed; adding metadata to the rootnode will break if the root gets switched around. 
> 
> I've been trying to read the class reference to find a good way to uniquely identify a scene but so far I haven't seen a good option. I'm also going to investigate the uniqueness of each scene's UndoRedo object when I get home tomorrow.

**Comment by Hotklou2404** [comment]
I've just thought of this. Blender uses `H` to hide stuff and `Alt + H` to unhide everything. So `Alt + H` might be nice.

**Comment by SheepCommander** [comment]
Alt+H was actually in my first commit funnily enough, but I removed it because I haven't figured out a useable implementation yet. 

In blender it's alright to naively show and hide all other nodes, but in Godot (particularly in a large UI scene) it would be unacceptable unless i force all developers to use an `_on_ready()` method to hide what's supposed to be hidden.

(Honestly using on_ready to be extra sure all the nodes are properly configured is a great idea, but I suspect that most developers do not do this)

**Comment by SheepCommander** [comment]
Incase this helps a future developer (or me);

Each "Scene" (global context, scene1, scene2, and resource context) have their own UndoRedo objects, and each UndoRedo object has a unique ID.

The EditorUndoRedoManager object manages all UndoRedo objects used by the editor. You can access it with
```gdscript
extends EditorPlugin
var undo_redo = get_undo_redo()
```

You can now use `undo_redo.get_object_history_id(my_node)` which will return the integer ID of the UndoRedo object that manages that node. Passing any node from the same scene will return the same ID number.

You can now use this ID to uniquely identify nodes, incase you have to implement your own per-scene cache and crap!

> I'm going to try to get this Issue #2 resolved in the next few hours
