### ISSUE TITLE
Hotkey does not work when the Scene dock is selected.

### ISSUE THREAD

**Issue by SheepCommander** [SheepCommander/gd-SoloVisibility#3]
> Hotkey does not work when the Scene dock is selected.

Any developers have any idea how to handle this?

The issue is that using the `_input()` method means that inputs will be detected even while writing code inside the Script editor, so I switched to `_forward_canvas_gui_input` and `_forward_3d_gui_input`, however those only respond when the user clicks inside of the viewport.

**Comment by SheepCommander** [comment]
After doing a lot of testing, I can confirm that `.get_script .get_base .has_focus` will return true if you are currently editing a script.

However, if you have THIS THING SELECTED

![image](https://github.com/SheepCommander/gd-SoloVisibility/assets/66646514/df4185e0-5cac-4bef-9bbb-4d7813afc43e)

That thing will be the control that has_focus, and if you press the hotkey with that selected it will activate.

It will also activate if you have the FileSystem or any other dock selected...

I conclude that the editor makes it impossible for me to limit the hotkey to only work in 2D, 3D, and Scene dock, and the only thing i can do is make issues to https://github.com/godotengine/godot-proposals/

> <details>
>    <summary> "Me going feral here" </summary>
> 
> ```gdscript
> 		printt( # I am going insane i will go feral
> 		EditorInterface.get_script_editor().get_current_editor().get_base_editor(),
> 		EditorInterface.get_script_editor().get_current_editor().get_base_editor().has_focus(),
> 		EditorInterface.get_script_editor().get_current_editor(),
> 		EditorInterface.get_script_editor().get_current_editor().has_focus(),
> 		EditorInterface.get_script_editor(),
> 		EditorInterface.get_script_editor().has_focus(),
> 		EditorInterface.get_editor_main_screen(),
> 		EditorInterface.get_editor_main_screen().has_focus(),
> 		)
> 		print(EditorInterface.get_base_control().get_children())
> 		print(EditorInterface.get_base_control().find_child("VBoxContainer")
>
>
> func _input(event: InputEvent) -> void:
> 	if (HideShortcut.is_match(event) and event.is_pressed() and !event.is_echo()):
> 		var open_script = EditorInterface.get_script_editor().get_current_editor().get_base_editor()
> 		if open_script:
> 			if not open_script.has_focus():
> 				commit_hide_nodes()
> ```
> </details>

**Comment by ShepChromebook** [comment]
This was fixed with graceful advice from the Godot Engine discord! (#plugins, @\TheDex)

Now the hotkey only activates when:
- 3D Main Screen (the 3D tab at the top middle) is selected
- 2D Main Screen is selected
and
- 2D Viewport is focused
- 3D Viewport is focused
- Scene window (the scene node tree editor) is focused

**Comment by ShepChromebook** [comment]
`[Screen recording 2024-06-04 11.18.51 AM.webm](https://github.com/SheepCommander/gd-SoloVisibility/assets/93790365/add45e8b-086c-40fd-972b-e1e122c8b684)`

[Screen recording 2024-06-04 11.18.51 AM.webm](https://github.com/SheepCommander/gd-SoloVisibility/assets/93790365/add45e8b-086c-40fd-972b-e1e122c8b684)
